import DOMPurify from 'dompurify';

/**
 * Global sanitization configuration for WakiliWorld
 * All user-generated content must be sanitized before rendering
 */

// Safe fields that don't need sanitization (IDs, numbers, dates, booleans, enums)
const SAFE_FIELDS = new Set([
  'id',
  '$id',
  'user_id',
  'owner',
  'createdBy',
  'created_by',
  'created_at',
  '$createdAt',
  'updated_at',
  '$updatedAt',
  'organization_id',
  'client_id',
  'advocate_id',
  'court_id',
  'assigned_to',
  'case_id',
  'case',
  'room',
  'sender',
  'owner_id',
  'shared_with',
  'participants',
  'role',
  'status',
  'priority',
  'total_amount',
  'amount',
  'total',
  'tax',
  'amount_due',
  'count',
  'results',
  'data',
  'length',
  'map',
  'filter',
  'reduce',
  'sort',
  'push',
  'pop',
  // Contact fields (may contain PII but are safe from XSS as plain text)
  'phone_number',
  'alternative_phone_number',
  'date_of_birth',
  'id_number',
  'passport_number',
  'address',
  'occupation',
  'marital_status',
  'nationality',
  'gender',
  // Financial fields
  'invoice_number',
  'clientName',
  'client_address',
  'crn',
  'accountNumber',
  'accountName',
  'bankDetail',
  'terms',
  'signature',
  'category',
  'line_items',
  'items',
  'description',
  'rate',
  'hours',
  'unit_price',
  'quantity',
  'subtotal',
  'discount',
  'payment_method',
  'transaction_id',
  'subscription_id',
  'plan_type',
  'price',
  'billing_cycle',
  'next_billing_date',
  'trial_end',
  'cancelled_at',
  'expires_at',
  'reminder_date',
  'deadline',
  'start_date',
  'end_date',
  'due_date',
  'completed_at',
  'archived',
  'favorite',
  'color',
  'label',
  'tags',
  'attachments',
  'version',
  'checksum',
  'hash',
  'metadata',
  // User profile fields
  'email',
  'username',
  'name',
  'avatar',
  'avatar_url',
  'profile_picture',
  'first_name',
  'last_name',
  'middle_name',
  'prefix',
  'suffix',
  'title',
  'honorific',
  'nickname',
  'display_name',
  'full_name',
  'bio',
  'practice_areas',
  'timezone',
  'notifications',
  'permissions',
  // Document fields
  'file',
  'file_path',
  'file_url',
  'download_url',
  'stream_url',
  'cdn_url',
  'bucket',
  'key',
  'path',
  'filename',
  'extension',
  'mime_type',
  'content_type',
  'size',
  'width',
  'height',
  // Media fields
  'duration',
  'bitrate',
  'format',
  'codec',
  'encoding',
  'compression',
  'quality',
  'resolution',
  'frame_rate',
  'sample_rate',
  'channels',
  'language',
  'country',
  'region',
  'city',
  'state',
  'province',
  'zip',
  'postal_code',
  // Authentication fields (safe as they're not rendered)
  'password',
  'api_key',
  'secret',
  'private_key',
  'public_key',
  'key',
  'salt',
  'hash',
  'iv',
  'nonce',
  'signature',
  'certificate',
  'fingerprint',
  'session_id',
  'verification_token',
  'reset_token',
  'code',
  'otp',
  'mfa_enabled',
  'two_factor_enabled',
  'backup_codes',
  'recovery_codes',
  'security_questions',
  // Audit fields
  'log_entries',
  'audit_trail',
  'ip_address',
  'user_agent',
  'device_id',
  'location',
  'coordinates',
  'latitude',
  'longitude',
  'altitude',
  'accuracy',
  'heading',
  'speed',
  'last_login',
  'last_seen',
  'last_active',
  'last_updated',
  'deleted_at',
  'archived_at',
  'published_at',
  'submitted_at',
  'approved_at',
  'rejected_at',
  'processed_at',
  'shipped_at',
  'delivered_at',
  'received_at',
  'read_at',
  'viewed_at',
  'clicked_at',
  'downloaded_at',
  'uploaded_at',
  'synced_at',
  'connected_at',
  'paired_at',
  'linked_at',
  'unlinked_at',
  'blocked_at',
  'suspended_at',
  'revoked_at',
  'canceled_at',
  'terminated_at',
  'paused_at',
  'resumed_at',
  'started_at',
  'stopped_at',
  'restarted_at',
  // Identifiers
  'uuid',
  'uid',
  'guid',
  'slug',
  'handle',
  // URLs and media
  'url',
  'uri',
  'website',
  'blog',
  'rss',
  'feed',
  'image',
  'avatar_url',
  'photo',
  'picture',
  'logo',
  'icon',
  'banner',
  'cover',
  'background',
  'thumbnail',
  'preview',
  // Misc numeric/boolean
  'number',
  'value',
  'count',
  'percentage',
  'ratio',
  'rate',
  'quantity',
  'unit',
  'unit_price',
  'per',
  'each',
  'is_',
  'has_',
  'can_',
  'should_',
  'will_',
  'would_',
  'enable',
  'disabled',
  'active',
  'inactive',
  'online',
  'offline',
  'visible',
  'hidden',
  'public',
  'private',
  'confidential',
]);

/**
 * Recursively sanitize all string values in an object/array
 * Skips safe fields to preserve data integrity
 */
export const sanitizeResponse = (data) => {
  if (typeof data === 'string') {
    return DOMPurify.sanitize(data, {
      ALLOWED_TAGS: [
        'b',
        'i',
        'em',
        'strong',
        'a',
        'p',
        'br',
        'ul',
        'ol',
        'li',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
      ],
      ALLOWED_ATTR: ['href', 'target', 'rel'],
      ALLOW_DATA_ATTR: false,
      ALLOWED_URI_REGEXP: /^https?:\/\//,
    });
  }

  if (Array.isArray(data)) {
    return data.map((item) => sanitizeResponse(item));
  }

  if (typeof data === 'object' && data !== null) {
    const sanitized = {};
    for (const [key, value] of Object.entries(data)) {
      // Check if this is a safe field that doesn't need sanitization
      const isSafe =
        SAFE_FIELDS.has(key) ||
        key.endsWith('_id') ||
        key.startsWith('is_') ||
        key.startsWith('has_') ||
        key.startsWith('can_') ||
        typeof value === 'number' ||
        typeof value === 'boolean' ||
        value === null ||
        value === undefined;

      if (isSafe) {
        sanitized[key] = value;
      } else if (typeof value === 'string') {
        sanitized[key] = DOMPurify.sanitize(value, {
          ALLOWED_TAGS: ['b', 'i', 'em', 'strong', 'a', 'p', 'br', 'ul', 'ol', 'li'],
          ALLOWED_ATTR: ['href', 'target', 'rel'],
          ALLOW_DATA_ATTR: false,
        });
      } else if (typeof value === 'object' && value !== null) {
        sanitized[key] = sanitizeResponse(value);
      } else {
        sanitized[key] = value;
      }
    }
    return sanitized;
  }

  return data;
};

export default DOMPurify;
